name: ai_trainer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # BLE + permissions + utils
  flutter_blue_plus: ^1.32.7
  permission_handler: ^11.4.0
  intl: ^0.19.0
  http: ^1.2.2
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  # UI icons
  cupertino_icons: ^1.0.8

  # If you use a custom bottom sheet package in your code, uncomment this:
  # bottom_sheet: ^4.0.0  # enable if referenced in code

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
